apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multi-nic-network
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"multinic.fms.io/v1","kind":"MultiNicNetwork","metadata":{"name":"multi-nic-network"},"spec":{"attachPolicy":{"strategy":""},"ipam":"{\n \"type\":\"host-device-ipam\"\n}\n","masterNets":["10.241.132.0/24","10.241.131.0/24"],"plugin":{"cniVersion":"0.3.1","dns":{},"type":"mellanox"}}}
  finalizers:
    - finalizers.multinicnetwork.multinic.fms.io
spec:
  attachPolicy:
    strategy: ''
  ipam: |
    {
      "type": "host-device-ipam"
    }
  masterNets:
    - 10.241.132.0/24
    - 10.241.131.0/24
  plugin:
    cniVersion: 0.3.1
    dns: {}
    type: mellanox
status:
  computeResults: []
  configStatus: Success
  discovery:
  routeStatus: N/A
